SELECT YEAR(O.SALES_DATE) YEAR, MONTH(O.SALES_DATE) MONTH, COUNT(DISTINCT(O.USER_ID)) PURCHASED_USERS, ROUND(COUNT(DISTINCT(O.USER_ID)) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = '2021'), 1) PURCHASED_RATIO FROM ONLINE_SALE O
JOIN USER_INFO U ON U.USER_ID = O.USER_ID AND YEAR(U.JOINED) = '2021' 
GROUP BY MONTH 
ORDER BY YEAR, MONTH;