SELECT H.HISTORY_ID, 
       ROUND(C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * 
       (100 - IFNULL(P.DISCOUNT_RATE, 0)) / 100, 0) AS FEE 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = H.CAR_ID 
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
ON P.PLAN_ID = (SELECT PLAN_ID FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
               WHERE CAR_TYPE = '트럭' AND 
             REGEXP_REPLACE(DURATION_TYPE, '[^0-9]+', '') <= DATEDIFF(H.END_DATE, H.START_DATE) + 1 
               ORDER BY PLAN_ID DESC LIMIT 1)
WHERE C.CAR_TYPE = '트럭' 
ORDER BY FEE DESC, H.HISTORY_ID DESC;