WITH T AS (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31' 
    GROUP BY CAR_ID HAVING COUNT(CAR_ID) >= 5 
)
SELECT MONTH(C.START_DATE) MONTH, T.CAR_ID, COUNT(C.CAR_ID) RECORDS FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C 
JOIN T USING(CAR_ID) 
WHERE C.START_DATE >= '2022-08-01' AND C.START_DATE <= '2022-10-31'
GROUP BY MONTH(C.START_DATE), C.CAR_ID
ORDER BY MONTH, CAR_ID DESC;