WITH G AS (
    SELECT SUM(SCORE) SCORE, EMP_NO, YEAR FROM HR_GRADE 
    WHERE YEAR = 2022 
    GROUP BY EMP_NO 
)
SELECT G.SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL FROM G 
JOIN HR_EMPLOYEES E USING(EMP_NO) 
WHERE G.SCORE = (SELECT MAX(SCORE) FROM G);